# Generated by Django 4.0.3 on 2022-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/upload/product'),
        ),
        migrations.AlterField(
            model_name='items',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
